# Generated by Django 3.1.5 on 2021-07-21 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_auto_20210721_1727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_auto_20210721_1727'),
        ('tecnicolaboratorio', '0002_auto_20210721_1727'),
        ('representantetecnico', '0014_auto_20210720_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraspublicas',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bodega.bodega', verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.proveedor', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='compraspublicas',
            name='estado_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.estadotransaccion', verbose_name='Estado de compras'),
        ),
        migrations.AlterField(
            model_name='compraspublicasdetalle',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.stock', verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='desgloseinfomemensualdetalle',
            name='solicitud_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.solicituddetalle'),
        ),
        migrations.AlterField(
            model_name='informesmensuales',
            name='estado_informe',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.estadotransaccion'),
        ),
        migrations.AlterField(
            model_name='informesmensuales',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tecnicolaboratorio.laboratorio', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='informesmensuales',
            name='laboratorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='laboratorista'),
        ),
        migrations.AlterField(
            model_name='informesmensuales',
            name='mes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.mes', verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='informesmensualesdetalle',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.stock', verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='compra_publica_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.compraspublicasdetalle'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='informe_mensual_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.informesmensualesdetalle'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='solicitud_detalle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.solicituddetalle'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.stock'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo_movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.tipomovimientoinventario', verbose_name='Tipo de movimiento de inventario'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bodega.bodega', verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.estadotransaccion', verbose_name='Estados solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tecnicolaboratorio.laboratorio', verbose_name='Laboratorio'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='responsable_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.persona', verbose_name='Responsable de actividad'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.tipoactividad', verbose_name='Tipo de actividad'),
        ),
        migrations.AlterField(
            model_name='solicituddetalle',
            name='sustancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.sustancia', verbose_name='Sustancia'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bodega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bodega.bodega'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='laboratorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tecnicolaboratorio.laboratorio'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sustancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.sustancia'),
        ),
        migrations.AlterField(
            model_name='sustancia',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='representantetecnico.unidadmedida', verbose_name='Unidad de medida'),
        ),
    ]
