# Generated by Django 3.1.5 on 2021-08-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0017_auto_20210808_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='representantetecnico.stock'),
        ),
    ]
