# Generated by Django 3.1.5 on 2021-08-14 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0019_auto_20210812_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informesmensuales',
            name='laboratorista',
        ),
    ]
