# Generated by Django 3.1.5 on 2021-08-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0020_remove_informesmensuales_laboratorista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='solicitante',
        ),
    ]
