# Generated by Django 3.1.5 on 2021-08-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0021_remove_solicitud_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadotransaccion',
            name='estado',
            field=models.CharField(max_length=100, unique=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre de empresa'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='nombre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre de unidad de medida'),
        ),
        migrations.AddConstraint(
            model_name='compraspublicasdetalle',
            constraint=models.UniqueConstraint(fields=('compra', 'stock'), name='Unico stock de sustancia por compra'),
        ),
        migrations.AddConstraint(
            model_name='informesmensuales',
            constraint=models.UniqueConstraint(fields=('laboratorio', 'mes', 'year'), name='Unica informe por mes y año en un laboratorio'),
        ),
        migrations.AddConstraint(
            model_name='informesmensualesdetalle',
            constraint=models.UniqueConstraint(fields=('informe', 'stock'), name='Unico stock de sustancia por informe'),
        ),
        migrations.AddConstraint(
            model_name='solicituddetalle',
            constraint=models.UniqueConstraint(fields=('solicitud', 'sustancia'), name='Unica sustancia por laboratorio'),
        ),
    ]
