# Generated by Django 3.1.5 on 2021-08-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicolaboratorio', '0015_auto_20210813_1539'),
        ('representantetecnico', '0022_auto_20210814_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desgloseinfomemensualdetalle',
            name='solicitud_detalle',
        ),
        migrations.AddField(
            model_name='desgloseinfomemensualdetalle',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tecnicolaboratorio.proyecto', verbose_name='Proyecto'),
        ),
    ]
