# Generated by Django 3.1.5 on 2021-08-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0023_auto_20210814_1845'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='desgloseinfomemensualdetalle',
            constraint=models.UniqueConstraint(fields=('informe_mensual_detalle', 'proyecto'), name='Unico proyecto por cada detalle de informe'),
        ),
    ]
