# Generated by Django 3.1.5 on 2021-08-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0026_auto_20210822_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='documento_solicitud',
        ),
    ]
