# Generated by Django 3.1.5 on 2021-08-26 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0027_remove_solicitud_documento_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='documento_solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='representantetecnico.repositorio'),
        ),
    ]
