# Generated by Django 3.1.5 on 2021-08-26 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0028_solicitud_documento_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='documento_solicitud',
        ),
    ]
