# Generated by Django 3.1.5 on 2021-08-26 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0030_solicitud_documento_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRepositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo de repositorio',
                'verbose_name_plural': 'Tipos de positorios',
                'db_table': 'tipo_repositorio',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='repositorio',
            name='is_recicle_bin',
        ),
        migrations.AddField(
            model_name='repositorio',
            name='tipo_repositorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='representantetecnico.tiporepositorio'),
        ),
    ]
