# Generated by Django 3.1.5 on 2021-08-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0031_auto_20210826_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiporepositorio',
            options={'ordering': ['id'], 'verbose_name': 'Tipo de repositorio', 'verbose_name_plural': 'Tipos de repositorios'},
        ),
    ]
