# Generated by Django 3.1.5 on 2021-07-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Persona',
                'verbose_name_plural': 'Tipo de Personas',
                'db_table': 'tipo_persona',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.tipopersona', verbose_name='Tipo de persona'),
        ),
    ]
