# Generated by Django 3.1.5 on 2021-07-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_persona_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
