# Generated by Django 3.1.5 on 2021-07-24 22:48

import core.base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210724_1530'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.base.models.MyUserManager()),
            ],
        ),
    ]
