# Generated by Django 3.1.5 on 2021-08-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20210804_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_creation',
        ),
    ]
