# Generated by Django 3.1.5 on 2021-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_user_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_info_update',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
    ]
