# Generated by Django 3.1.5 on 2021-08-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20210808_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='codeconfirm',
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
