# Generated by Django 3.1.5 on 2021-08-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20210817_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
