# Generated by Django 3.1.5 on 2021-08-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0003_auto_20210721_1727'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bodega',
            constraint=models.UniqueConstraint(fields=('responsable',), name='Unico reponsable con unica bodega'),
        ),
    ]
