# Generated by Django 3.1.5 on 2021-08-23 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0005_auto_20210814_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_bodega_bodega_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_bodega_bodega_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
