# Generated by Django 3.1.5 on 2021-07-26 03:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0010_auto_20210724_1748'),
        ('tecnicolaboratorio', '0002_auto_20210721_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de laboratorio')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('fecha_inicio', models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 25, 22, 4, 45, 881709), null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 25, 22, 4, 45, 881709), null=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tecnicolaboratorio.laboratorio', verbose_name='Laboratorio')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.persona', verbose_name='Responsable')),
                ('user_creation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_tecnicolaboratorio_proyecto', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_tecnicolaboratorio_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
                'ordering': ['id'],
            },
        ),
    ]
