# Generated by Django 3.1.5 on 2021-07-31 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicolaboratorio', '0005_auto_20210731_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 0, 38, 0, 135017), null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 0, 38, 0, 135017), null=True),
        ),
    ]
