# Generated by Django 3.1.5 on 2021-08-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicolaboratorio', '0008_auto_20210731_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='responsable',
        ),
    ]
