# Generated by Django 3.1.5 on 2021-08-09 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representantetecnico', '0017_auto_20210808_1418'),
        ('tecnicolaboratorio', '0010_proyecto_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipo_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='representantetecnico.tipoactividad', verbose_name='Tipo de proyecto'),
        ),
    ]
