# Generated by Django 3.1.5 on 2021-08-11 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tecnicolaboratorio', '0011_proyecto_tipo_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
