# Generated by Django 3.1.5 on 2021-08-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicolaboratorio', '0012_auto_20210811_1717'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='laboratorio',
            constraint=models.UniqueConstraint(fields=('responsable',), name='Unico reponsable con unico laboratorio'),
        ),
    ]
