# Generated by Django 3.1.5 on 2021-08-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicolaboratorio', '0014_auto_20210813_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('nombre', 'laboratorio'), name='Unico proyecto por laboratorio'),
        ),
    ]
