# Generated by Django 3.1.5 on 2021-08-23 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tecnicolaboratorio', '0015_auto_20210813_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_tecnicolaboratorio_laboratorio_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_tecnicolaboratorio_laboratorio_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='user_creation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation_tecnicolaboratorio_proyecto_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='user_updated',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_tecnicolaboratorio_proyecto_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
